module.exports.Forecast=function(req,res){
    res.render('Forecast');
};
module.exports.AboutUs=function(req,res){
    res.render('AboutUs');
};
module.exports.Articles=function(req,res){
    res.render('Articles');
};
module.exports.contact=function(req,res){
    res.render('contact');
};
